# Generated by Django 5.0.1 on 2024-02-25 16:27

import django.db.models.deletion
import registrationprofile.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("basicuser", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistrationProfile",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        default=registrationprofile.models.code_generator, max_length=5
                    ),
                ),
            ],
        ),
    ]
